In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/original_data.csv")

df

,id,title,type,country,release_year,genre,description
0,1,The Food Journey,Movie,Sweden,2020,Documentary,A documentary about food culture in Sweden
1,2,Kitchen Secrets,TV Show,USA,2021,Reality,A show about restaurants and cooking
2,3,Nordic Taste,Movie,Denmark,2019,Drama,A story about a chef in Copenhagen
3,4,Hotel Nights,TV Show,Sweden,2022,Drama,A series about life inside a hotel
4,5,Street Food Stories,Movie,Thailand,2023,Documentary,A documentary about street food and people

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            5 non-null      int64
 1   title         5 non-null      str
 2   type          5 non-null      str
 3   country       5 non-null      str
 4   release_year  5 non-null      int64
 5   genre         5 non-null      str
 6   description   5 non-null      str
dtypes: int64(2), str(5)
memory usage: 412.0 bytes

In [5]:
df.isnull().sum()

id              0
title           0
type            0
country         0
release_year    0
genre           0
description     0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
cleaned_df = df.copy()

cleaned_df

,id,title,type,country,release_year,genre,description
0,1,The Food Journey,Movie,Sweden,2020,Documentary,A documentary about food culture in Sweden
1,2,Kitchen Secrets,TV Show,USA,2021,Reality,A show about restaurants and cooking
2,3,Nordic Taste,Movie,Denmark,2019,Drama,A story about a chef in Copenhagen
3,4,Hotel Nights,TV Show,Sweden,2022,Drama,A series about life inside a hotel
4,5,Street Food Stories,Movie,Thailand,2023,Documentary,A documentary about street food and people

In [8]:
cleaned_df.columns = (
    cleaned_df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
)

cleaned_df.columns

Index(['id', 'title', 'type', 'country', 'release_year', 'genre',
       'description'],
      dtype='str')

In [9]:
cleaned_df = cleaned_df.drop_duplicates()

cleaned_df

,id,title,type,country,release_year,genre,description
0,1,The Food Journey,Movie,Sweden,2020,Documentary,A documentary about food culture in Sweden
1,2,Kitchen Secrets,TV Show,USA,2021,Reality,A show about restaurants and cooking
2,3,Nordic Taste,Movie,Denmark,2019,Drama,A story about a chef in Copenhagen
3,4,Hotel Nights,TV Show,Sweden,2022,Drama,A series about life inside a hotel
4,5,Street Food Stories,Movie,Thailand,2023,Documentary,A documentary about street food and people

In [10]:
def row_to_text(row):
    return f"""
    Titel: {row['title']}
    Typ: {row['type']}
    Land: {row['country']}
    År: {row['release_year']}
    Genre: {row['genre']}
    Beskrivning: {row['description']}
    """

cleaned_df["text"] = cleaned_df.apply(row_to_text, axis=1)

cleaned_df[["title", "text"]]

                 title                                               text
0     The Food Journey  \n    Titel: The Food Journey\n    Typ: Movie\...
1      Kitchen Secrets  \n    Titel: Kitchen Secrets\n    Typ: TV Show...
2         Nordic Taste  \n    Titel: Nordic Taste\n    Typ: Movie\n   ...
3         Hotel Nights  \n    Titel: Hotel Nights\n    Typ: TV Show\n ...
4  Street Food Stories  \n    Titel: Street Food Stories\n    Typ: Mov...

In [11]:
cleaned_df.to_csv("../data/cleaned_data.csv", index=False)

# Data preprocessing

I den här notebooken undersöker, rengör och transformerar vi vår CSV-data innan den används i RAG-systemet.